# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ebcac5df18b64c3e09224edf80622c983cf5f4021cfc6c39d2ec18ce1be03e74988e4237f1cced1b7b255f33444e96fa4160bf91c67c6bf41577606238b9da3f

test:
  secret_key_base: 2bbda1a043290b93864ae5ae1f59eb2ac65b3f3e01d8b895c0bf61e4ee4a4f99309dec65cc3f6818a01b3048ce48e9a9905658855f66a30dba9d06687d238ab5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
